### ISSUE TITLE
Single piece carrying

### ISSUE THREAD

**Issue by kartpat** [popabczhang/TangoBattleChess#7]
User should be able to carry only one piece at a time.

**Comment by kartpat** [comment]
Implemented a boolean as a part of the AR Camera because, the pieces themselves do not know if the camera is carrying at the moment. So the piece checks the script on AR camera for "isCarrying " flag. Check the takeMe.cs and networkedTouchBool.cs scripts.

**Comment by popabczhang** [comment]
nice
